# Generated by Django 3.0.8 on 2020-09-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AGPG', 'Aguardando pagamento'), ('PGCF', 'Pagamento confirmado')], default='AGPG', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estoque_models.Venda')),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='estoque_models.Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estoque_models.Venda')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(choices=[('DINH', 'Dinheiro'), ('CDEB', 'Cartão de Débito'), ('CCRE', 'Cartão de Crédito'), ('BLTO', 'Boleto')], max_length=4)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estoque_models.Pagamento')),
            ],
        ),
    ]
