# Generated by Django 3.0.8 on 2020-09-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='total_a_pagar',
        ),
    ]
