# Generated by Django 3.0.8 on 2020-09-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='endereco_entrega',
        ),
    ]
