# Generated by Django 3.0.8 on 2020-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_models', '0002_remove_venda_endereco_entrega'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
